/**
 * AUTO-GENERATED BY ts-schema-generator - DO NOT EDIT!
 *
 * 2020-02-09T17:04:02.200Z
 */

/* eslint-disable */

export enum CountryEnum {
  Ad = "AD",
  Ae = "AE",
  Af = "AF",
  Ag = "AG",
  Ai = "AI",
  Al = "AL",
  Am = "AM",
  Ao = "AO",
  Aq = "AQ",
  Ar = "AR",
  As = "AS",
  At = "AT",
  Au = "AU",
  Aw = "AW",
  Ax = "AX",
  Az = "AZ",
  Ba = "BA",
  Bb = "BB",
  Bd = "BD",
  Be = "BE",
  Bf = "BF",
  Bg = "BG",
  Bh = "BH",
  Bi = "BI",
  Bj = "BJ",
  Bl = "BL",
  Bm = "BM",
  Bn = "BN",
  Bo = "BO",
  Bq = "BQ",
  Br = "BR",
  Bs = "BS",
  Bt = "BT",
  Bv = "BV",
  Bw = "BW",
  By = "BY",
  Bz = "BZ",
  Ca = "CA",
  Cc = "CC",
  Cd = "CD",
  Cf = "CF",
  Cg = "CG",
  Ch = "CH",
  Ci = "CI",
  Ck = "CK",
  Cl = "CL",
  Cm = "CM",
  Cn = "CN",
  Co = "CO",
  Cr = "CR",
  Cu = "CU",
  Cv = "CV",
  Cw = "CW",
  Cx = "CX",
  Cy = "CY",
  Cz = "CZ",
  De = "DE",
  Dj = "DJ",
  Dk = "DK",
  Dm = "DM",
  Do = "DO",
  Dz = "DZ",
  Ec = "EC",
  Ee = "EE",
  Eg = "EG",
  Eh = "EH",
  Er = "ER",
  Es = "ES",
  Et = "ET",
  Fi = "FI",
  Fj = "FJ",
  Fk = "FK",
  Fm = "FM",
  Fo = "FO",
  Fr = "FR",
  Ga = "GA",
  Gb = "GB",
  Gd = "GD",
  Ge = "GE",
  Gf = "GF",
  Gg = "GG",
  Gh = "GH",
  Gi = "GI",
  Gl = "GL",
  Gm = "GM",
  Gn = "GN",
  Gp = "GP",
  Gq = "GQ",
  Gr = "GR",
  Gs = "GS",
  Gt = "GT",
  Gu = "GU",
  Gw = "GW",
  Gy = "GY",
  Hk = "HK",
  Hm = "HM",
  Hn = "HN",
  Hr = "HR",
  Ht = "HT",
  Hu = "HU",
  Id = "ID",
  Ie = "IE",
  Il = "IL",
  Im = "IM",
  In = "IN",
  Io = "IO",
  Iq = "IQ",
  Ir = "IR",
  Is = "IS",
  It = "IT",
  Je = "JE",
  Jm = "JM",
  Jo = "JO",
  Jp = "JP",
  Ke = "KE",
  Kg = "KG",
  Kh = "KH",
  Ki = "KI",
  Km = "KM",
  Kn = "KN",
  Kp = "KP",
  Kr = "KR",
  Kw = "KW",
  Ky = "KY",
  Kz = "KZ",
  La = "LA",
  Lb = "LB",
  Lc = "LC",
  Li = "LI",
  Lk = "LK",
  Lr = "LR",
  Ls = "LS",
  Lt = "LT",
  Lu = "LU",
  Lv = "LV",
  Ly = "LY",
  Ma = "MA",
  Mc = "MC",
  Md = "MD",
  Me = "ME",
  Mf = "MF",
  Mg = "MG",
  Mh = "MH",
  Mk = "MK",
  Ml = "ML",
  Mm = "MM",
  Mn = "MN",
  Mo = "MO",
  Mp = "MP",
  Mq = "MQ",
  Mr = "MR",
  Ms = "MS",
  Mt = "MT",
  Mu = "MU",
  Mv = "MV",
  Mw = "MW",
  Mx = "MX",
  My = "MY",
  Mz = "MZ",
  Na = "NA",
  Nc = "NC",
  Ne = "NE",
  Nf = "NF",
  Ng = "NG",
  Ni = "NI",
  Nl = "NL",
  No = "NO",
  Np = "NP",
  Nr = "NR",
  Nu = "NU",
  Nz = "NZ",
  Om = "OM",
  Pa = "PA",
  Pe = "PE",
  Pf = "PF",
  Pg = "PG",
  Ph = "PH",
  Pk = "PK",
  Pl = "PL",
  Pm = "PM",
  Pn = "PN",
  Pr = "PR",
  Ps = "PS",
  Pt = "PT",
  Pw = "PW",
  Py = "PY",
  Qa = "QA",
  Re = "RE",
  Ro = "RO",
  Rs = "RS",
  Ru = "RU",
  Rw = "RW",
  Sa = "SA",
  Sb = "SB",
  Sc = "SC",
  Sd = "SD",
  Se = "SE",
  Sg = "SG",
  Sh = "SH",
  Si = "SI",
  Sj = "SJ",
  Sk = "SK",
  Sl = "SL",
  Sm = "SM",
  Sn = "SN",
  So = "SO",
  Sr = "SR",
  Ss = "SS",
  St = "ST",
  Sv = "SV",
  Sx = "SX",
  Sy = "SY",
  Sz = "SZ",
  Tc = "TC",
  Td = "TD",
  Tf = "TF",
  Tg = "TG",
  Th = "TH",
  Tj = "TJ",
  Tk = "TK",
  Tl = "TL",
  Tm = "TM",
  Tn = "TN",
  To = "TO",
  Tr = "TR",
  Tt = "TT",
  Tv = "TV",
  Tw = "TW",
  Tz = "TZ",
  Ua = "UA",
  Ug = "UG",
  Um = "UM",
  Us = "US",
  Uy = "UY",
  Uz = "UZ",
  Va = "VA",
  Vc = "VC",
  Ve = "VE",
  Vg = "VG",
  Vi = "VI",
  Vn = "VN",
  Vu = "VU",
  Wf = "WF",
  Ws = "WS",
  Ye = "YE",
  Yt = "YT",
  Za = "ZA",
  Zm = "ZM",
  Zw = "ZW"
}

export enum CurrencyEnum {
  Cad = "CAD",
  Cny = "CNY",
  Eur = "EUR",
  Gbp = "GBP",
  Jpy = "JPY",
  Mxn = "MXN",
  Usd = "USD"
}

export enum DataTypeEnum {
  Boolean = "Boolean",
  Number = "Number",
  String = "String"
}

export enum EmployeeLevelEnum {
  Manager = 1,
  SeniorManager = 2,
  SeniorStaff = 3,
  Staff = 4,
  Unknown = 5
}

export enum EmployeeTypeEnum {
  Contractor = 1,
  FullTimeHourly = 2,
  FullTimeSalaried = 3,
  PartTimeHourly = 4,
  PartTimeSalaried = 5,
  Unknown = 6
}

export enum FinancialStatusEnum {
  Authorized = 1,
  Paid = 2,
  PartiallyPaid = 3,
  PartiallyRefunded = 4,
  Pending = 5,
  Refunded = 6,
  Void = 7
}

export enum InventoryConditionEnum {
  New = 1,
  Refurbished = 2,
  Unknown = 3,
  Used = 4
}

export enum InventoryPolicyEnum {
  Deny = 1,
  Allow = 2
}

export enum InventoryRequestReasonEnum {
  Unknown = 1
}

export enum LocaleEnum {
  En = "EN",
  Cn = "CN",
  De = "DE",
  It = "IT",
  Fr = "FR",
  Es = "ES"
}

export enum OrderCancelReasonEnum {
  Customer = 1,
  Declined = 2,
  Fraud = 3,
  Inventory = 4,
  Other = 5
}

export enum OrderReturnReasonEnum {
  AccidentallyPurchased = 1,
  Defective = 2,
  NotAsDescribed = 3,
  Refused = 4,
  UnauthorizedPurchase = 5,
  Unknown = 6,
  Unwanted = 7
}

export enum PackageTypeEnum {
  Envelope = 1,
  LargeBox = 2,
  MediumBox = 3,
  Pallet = 4,
  SmallBox = 5
}

export enum PaymentTermEnum {
  Cod = 1,
  Net10 = 2,
  Net120 = 3,
  Net150 = 4,
  Net180 = 5,
  Net210 = 6,
  Net240 = 7,
  Net270 = 8,
  Net30 = 9,
  Net300 = 10,
  Net330 = 11,
  Net360 = 12,
  Net45 = 13,
  Net60 = 14,
  Net7 = 15,
  Net90 = 16,
  OnePercent10Net30 = 17,
  Pia = 18
}

export enum ProductIssueStatusEnum {}

export enum ProductIssueTypeEnum {}

export enum PurchaseOrderStatusEnum {
  Pending = 1,
  Unshipped = 2,
  PartiallyShipped = 3,
  Shipped = 4,
  Unfulfillable = 5,
  Canceled = 6,
  Unknown = 7
}

export enum ReturnDepositionEnum {
  CarrierDamaged = 1,
  CustomerDamaged = 2,
  Defective = 3,
  Sellable = 4
}

export enum ReturnStatusEnum {
  Failure = 1,
  Pending = 2,
  Success = 3
}

export enum RoleEnum {
  Administrator = "Administrator",
  CustomerService = "CustomerService",
  Developer = "Developer",
  Listing = "Listing",
  Marketing = "Marketing",
  Shipping = "Shipping",
  Supplier = "Supplier",
  Wholesale = "Wholesale"
}

export enum SalesOrderStatusEnum {
  Pending = 1,
  Unshipped = 2,
  PartiallyShipped = 3,
  Shipped = 4,
  Unfulfillable = 5,
  Canceled = 6,
  Unknown = 7
}

export enum ScriptStatusEnum {
  Failure = "Failure",
  Pending = "Pending",
  Success = "Success"
}

export enum ShipmentEventTypeEnum {}

export enum ShipmentServiceEnum {
  AirFreight = 1,
  Expedited = 2,
  FreeEconomy = 3,
  NextDay = 4,
  OceanFreight = 5,
  SecondDay = 6,
  Standard = 7,
  Unknown = 8
}

export enum ShipmentStatusEnum {
  Accepted = 1,
  Delivered = 2,
  DeliveryAttempt = 3,
  Exception = 4,
  InTransit = 5,
  NotYetInSystem = 6,
  Unknown = 7
}

export enum TransactionErrorCodeEnum {
  CallIssuer = 1,
  CardDeclined = 2,
  ExpiredCard = 3,
  IncorrectAddress = 4,
  IncorrectCvc = 5,
  IncorrectNumber = 6,
  IncorrectZip = 7,
  InvalidCvc = 8,
  InvalidExpiryDate = 9,
  InvalidNumber = 10,
  PickUpCard = 11,
  ProcessingError = 12
}

export enum TransactionStatusEnum {
  Error = 1,
  Failure = 2,
  Pending = 3,
  Success = 4
}

export enum TransactionTypeEnum {
  Authorization = 1,
  Capture = 2,
  ReferralFee = 3,
  ReferralFeeRefund = 4,
  Sale = 5,
  SaleRefund = 6,
  SellingFee = 7,
  SellingFeeRefund = 8,
  TransactionFee = 9,
  TransactionFeeRefund = 10,
  Void = 11
}

export enum TransferCancelReasonEnum {
  Unknown = 1
}

export enum TransferReturnReasonEnum {}

export enum TransferStatusEnum {
  Cancelled = 1,
  Completed = 2,
  Deleted = 3,
  Error = 4,
  Partial = 5,
  Pending = 6
}

export enum UnitDimensionEnum {
  Centimeter = "Centimeter",
  Inch = "Inch"
}

export enum UnitWeightEnum {
  Gram = "Gram",
  Kilogram = "Kilogram",
  Ounce = "Ounce",
  Pound = "Pound"
}

export enum UserTokenTypeEnum {
  RefreshToken = "RefreshToken"
}

export enum WholesaleAccountChannelEnum {
  ByProject = 1,
  LocalStore = 2,
  OnlineStore = 3
}

export enum WholesaleAccountLevelEnum {
  Bronze = 1,
  Diamond = 2,
  Gold = 3,
  Platinum = 4,
  Silver = 5,
  Unknown = 6
}

export enum WholesaleAccountRoleEnum {
  Distributer = 1,
  EndUser = 2,
  Installer = 3,
  Unknown = 4
}

export enum WholesaleAccountStatusEnum {
  Declined = 1,
  Disabled = 2,
  Enabled = 3,
  Invited = 4
}

export enum WholesaleAccountTypeEnum {
  Corporation = 1,
  Llc = 2,
  Llp = 3,
  NonProfit = 4,
  Other = 5,
  Partnership = 6,
  SoleProprietor = 7
}

export enum WholesaleOrderStatusEnum {
  Pending = 1,
  Unshipped = 2,
  PartiallyShipped = 3,
  Shipped = 4,
  Unfulfillable = 5,
  Canceled = 6,
  Unknown = 7
}
