/**
 * AUTO-GENERATED BY ts-schema-generator - DO NOT EDIT!
 *
 * 2020-02-09T17:04:01.710Z
 */

/* eslint-disable */
import { JsonValue, SetRequired } from "type-fest";

/**
 * Test comment
 */
interface AddressType {
  /* test_comment */
  value: string;
  comment?: string | null;
  id?: number;
}
export interface AddressTypeSelect extends SetRequired<AddressType> {}
export interface AddressTypeInsert extends AddressType {}
export interface AddressTypeUpdate extends Partial<AddressType> {}

interface Attribute {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  dataType: string;
  name: string;
  description?: string | null;
  format?: string | null;
}
export interface AttributeSelect extends SetRequired<Attribute> {}
export interface AttributeInsert extends Attribute {}
export interface AttributeUpdate extends Partial<Attribute> {}

interface AttributeValue {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  attributeId: number;
  name: string;
  description?: string | null;
  position?: number;
}
export interface AttributeValueSelect extends SetRequired<AttributeValue> {}
export interface AttributeValueInsert extends AttributeValue {}
export interface AttributeValueUpdate extends Partial<AttributeValue> {}

interface CompetitorListing {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  operationCenterId: number;
  productId: number;
  referenceId: string;
  name?: string | null;
  image?: string | null;
}
export interface CompetitorListingSelect extends SetRequired<CompetitorListing> {}
export interface CompetitorListingInsert extends CompetitorListing {}
export interface CompetitorListingUpdate extends Partial<CompetitorListing> {}

interface CompetitorListingSnapshot {
  id?: number;
  operationCenterId: number;
  salesChannelId: number;
  competitorListingId: number;
  referenceId: string;
  referenceGroupId?: string | null;
  date: Date;
  reviews?: number | null;
  questions?: number | null;
  ratings?: number | null;
  rating?: number | null;
  price?: number | null;
  name: string;
  bulletpoints?: JsonValue | null;
  images?: JsonValue | null;
}
export interface CompetitorListingSnapshotSelect extends SetRequired<CompetitorListingSnapshot> {}
export interface CompetitorListingSnapshotInsert extends CompetitorListingSnapshot {}
export interface CompetitorListingSnapshotUpdate extends Partial<CompetitorListingSnapshot> {}

interface Country {
  value: string;
  comment?: string | null;
}
export interface CountrySelect extends SetRequired<Country> {}
export interface CountryInsert extends Country {}
export interface CountryUpdate extends Partial<Country> {}

interface Courier {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  name: string;
  description?: string | null;
  website?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface CourierSelect extends SetRequired<Courier> {}
export interface CourierInsert extends Courier {}
export interface CourierUpdate extends Partial<Courier> {}

interface Currency {
  value: string;
  comment?: string | null;
}
export interface CurrencySelect extends SetRequired<Currency> {}
export interface CurrencyInsert extends Currency {}
export interface CurrencyUpdate extends Partial<Currency> {}

interface Customer {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  salesChannelId: number;
  referenceId?: string | null;
  firstName?: string | null;
  lastName?: string | null;
  jobTitle?: string | null;
  jobDepartment?: string | null;
  email?: string | null;
  officeEmail?: string | null;
  phone?: string | null;
  officePhone?: string | null;
  fax?: string | null;
  locale?: string | null;
  currency?: string | null;
  birthday?: Date | null;
  taxvat?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  isAcceptMarketing?: boolean;
  isTaxExempt?: boolean;
  isEmailVerified?: boolean;
}
export interface CustomerSelect extends SetRequired<Customer> {}
export interface CustomerInsert extends Customer {}
export interface CustomerUpdate extends Partial<Customer> {}

interface DataType {
  value: string;
  comment?: string | null;
}
export interface DataTypeSelect extends SetRequired<DataType> {}
export interface DataTypeInsert extends DataType {}
export interface DataTypeUpdate extends Partial<DataType> {}

interface EmployeeLevel {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface EmployeeLevelSelect extends SetRequired<EmployeeLevel> {}
export interface EmployeeLevelInsert extends EmployeeLevel {}
export interface EmployeeLevelUpdate extends Partial<EmployeeLevel> {}

interface EmployeeType {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface EmployeeTypeSelect extends SetRequired<EmployeeType> {}
export interface EmployeeTypeInsert extends EmployeeType {}
export interface EmployeeTypeUpdate extends Partial<EmployeeType> {}

interface FinancialStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface FinancialStatusSelect extends SetRequired<FinancialStatus> {}
export interface FinancialStatusInsert extends FinancialStatus {}
export interface FinancialStatusUpdate extends Partial<FinancialStatus> {}

interface Inventory {
  productId: number;
  warehouseId: number;
  conditionId: number;
  location?: string | null;
  available?: number;
  incoming?: number;
  reserved?: number;
  temporary?: number;
  defective?: number;
  reason?: string | null;
  lowStockAt?: Date | null;
  lowStockThreshold?: number | null;
  isManageInvenotry?: boolean;
}
export interface InventorySelect extends SetRequired<Inventory> {}
export interface InventoryInsert extends Inventory {}
export interface InventoryUpdate extends Partial<Inventory> {}

interface InventoryCondition {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface InventoryConditionSelect extends SetRequired<InventoryCondition> {}
export interface InventoryConditionInsert extends InventoryCondition {}
export interface InventoryConditionUpdate extends Partial<InventoryCondition> {}

interface InventoryHistory {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  productId: number;
  warehouseId: number;
  sessionUser?: string | null;
  applicationName?: string | null;
  type: string;
  adjustment: number;
  conditionId: number;
  currentQuantity: number;
  previousQuantity: number;
  reason?: string | null;
}
export interface InventoryHistorySelect extends SetRequired<InventoryHistory> {}
export interface InventoryHistoryInsert extends InventoryHistory {}
export interface InventoryHistoryUpdate extends Partial<InventoryHistory> {}

interface InventoryPolicy {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface InventoryPolicySelect extends SetRequired<InventoryPolicy> {}
export interface InventoryPolicyInsert extends InventoryPolicy {}
export interface InventoryPolicyUpdate extends Partial<InventoryPolicy> {}

interface InventoryRequest {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  approvedAt?: Date | null;
  approvedBy?: number | null;
  receivedAt?: Date | null;
  receivedBy?: number | null;
  operationCenterId: number;
  reason: string;
  instruction?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  reasonEnumId?: number | null;
}
export interface InventoryRequestSelect extends SetRequired<InventoryRequest> {}
export interface InventoryRequestInsert extends InventoryRequest {}
export interface InventoryRequestUpdate extends Partial<InventoryRequest> {}

interface InventoryRequestItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  inventoryRequestId: number;
  productId: number;
  name: string;
  position: number;
  quantityRequested: number;
  quantityPicked?: number;
  quantityReturned?: number;
}
export interface InventoryRequestItemSelect extends SetRequired<InventoryRequestItem> {}
export interface InventoryRequestItemInsert extends InventoryRequestItem {}
export interface InventoryRequestItemUpdate extends Partial<InventoryRequestItem> {}

interface InventoryRequestReason {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface InventoryRequestReasonSelect extends SetRequired<InventoryRequestReason> {}
export interface InventoryRequestReasonInsert extends InventoryRequestReason {}
export interface InventoryRequestReasonUpdate extends Partial<InventoryRequestReason> {}

interface Listing {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  salesChannelId: number;
  productId?: number | null;
  referenceId: string;
  referenceGroupId?: string | null;
  name?: string | null;
  description?: string | null;
  barcode?: string | null;
  slug?: string | null;
  rating?: number | null;
  bulletpoints?: JsonValue | null;
  images?: JsonValue | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface ListingSelect extends SetRequired<Listing> {}
export interface ListingInsert extends Listing {}
export interface ListingUpdate extends Partial<Listing> {}

interface ListingReview {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  listingId: number;
  referenceId: string;
  referenceCustomerId: string;
  date: Date;
  title?: string | null;
  content?: string | null;
  reviewer?: string | null;
  rating: number;
  images?: JsonValue | null;
  videos?: JsonValue | null;
  helpfulCount?: number;
  isApproved: boolean;
  isVerified: boolean;
}
export interface ListingReviewSelect extends SetRequired<ListingReview> {}
export interface ListingReviewInsert extends ListingReview {}
export interface ListingReviewUpdate extends Partial<ListingReview> {}

interface ListingSnapshot {
  id?: number;
  operationCenterId: number;
  listingId: number;
  date: Date;
  sessions?: number;
  pageViews?: number;
  units?: number;
  unitsBusiness?: number;
  sales?: number;
  salesBusiness?: number;
  orders?: number;
  ordersBusiness?: number;
  orderItems?: number;
  orderItemsBusiness?: number;
  salesRank?: number | null;
  rating?: number | null;
  price?: number | null;
  reviews?: number | null;
  receivedRatings?: number | null;
  receivedRatingsAverage?: number | null;
}
export interface ListingSnapshotSelect extends SetRequired<ListingSnapshot> {}
export interface ListingSnapshotInsert extends ListingSnapshot {}
export interface ListingSnapshotUpdate extends Partial<ListingSnapshot> {}

interface ListingVariant {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  operationCenterId: number;
  listingId: number;
  referenceId: string;
  conditionId: number;
  inventoryPolicyId: number;
  currency?: string | null;
  price?: number | null;
  salesPrice?: number | null;
  isVenderFulfilled: boolean;
}
export interface ListingVariantSelect extends SetRequired<ListingVariant> {}
export interface ListingVariantInsert extends ListingVariant {}
export interface ListingVariantUpdate extends Partial<ListingVariant> {}

interface Locale {
  value: string;
  comment?: string | null;
}
export interface LocaleSelect extends SetRequired<Locale> {}
export interface LocaleInsert extends Locale {}
export interface LocaleUpdate extends Partial<Locale> {}

interface Marketplace {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  name: string;
  description?: string | null;
  website?: string | null;
  logo?: string | null;
  currency?: string | null;
  locale?: string | null;
  apiEndpoint?: string | null;
  apiMarketplaceId?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface MarketplaceSelect extends SetRequired<Marketplace> {}
export interface MarketplaceInsert extends Marketplace {}
export interface MarketplaceUpdate extends Partial<Marketplace> {}

interface OperationCenter {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  warehouseId: number;
  name: string;
  description?: string | null;
  logo?: string | null;
  currency?: string | null;
  moneyFormat?: string | null;
  moneyInEmailsFormat?: string | null;
  moneyWithCurrencyFormat?: string | null;
  moneyWithCurrencyInEmailsFormat?: string | null;
  locale?: string | null;
  timezone?: string | null;
  ianaTimezone?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface OperationCenterSelect extends SetRequired<OperationCenter> {}
export interface OperationCenterInsert extends OperationCenter {}
export interface OperationCenterUpdate extends Partial<OperationCenter> {}

interface OrderCancelReason {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface OrderCancelReasonSelect extends SetRequired<OrderCancelReason> {}
export interface OrderCancelReasonInsert extends OrderCancelReason {}
export interface OrderCancelReasonUpdate extends Partial<OrderCancelReason> {}

interface OrderReturnReason {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface OrderReturnReasonSelect extends SetRequired<OrderReturnReason> {}
export interface OrderReturnReasonInsert extends OrderReturnReason {}
export interface OrderReturnReasonUpdate extends Partial<OrderReturnReason> {}

interface PackageType {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface PackageTypeSelect extends SetRequired<PackageType> {}
export interface PackageTypeInsert extends PackageType {}
export interface PackageTypeUpdate extends Partial<PackageType> {}

interface PaymentAccount {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  operationCenterId: number;
  paymentMethodId: number;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface PaymentAccountSelect extends SetRequired<PaymentAccount> {}
export interface PaymentAccountInsert extends PaymentAccount {}
export interface PaymentAccountUpdate extends Partial<PaymentAccount> {}

interface PaymentMethod {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface PaymentMethodSelect extends SetRequired<PaymentMethod> {}
export interface PaymentMethodInsert extends PaymentMethod {}
export interface PaymentMethodUpdate extends Partial<PaymentMethod> {}

interface PaymentTerm {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface PaymentTermSelect extends SetRequired<PaymentTerm> {}
export interface PaymentTermInsert extends PaymentTerm {}
export interface PaymentTermUpdate extends Partial<PaymentTerm> {}

interface Product {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  discontinuedAt?: Date | null;
  discontinuedBy?: number | null;
  parentId?: number | null;
  imageId?: number | null;
  categoryId?: number | null;
  brandId?: number | null;
  name?: string | null;
  description?: string | null;
  modelNumber?: string | null;
  harmonizedSystemCode?: string | null;
  currency?: string | null;
  price?: number | null;
  cost?: number | null;
  weight?: number | null;
  weightUnit?: string | null;
  longestSide?: number | null;
  mediumSide?: number | null;
  shortestSide?: number | null;
  dimensionUnit?: string | null;
  warrantyInMonth?: number | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  isVirtual?: boolean;
  isTaxable?: boolean;
  isActive?: boolean;
}
export interface ProductSelect extends SetRequired<Product> {}
export interface ProductInsert extends Product {}
export interface ProductUpdate extends Partial<Product> {}

interface ProductAttachment {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  productId: number;
  typeId?: number | null;
  name: string;
  src: string;
  position?: number | null;
  mimeType?: string | null;
}
export interface ProductAttachmentSelect extends SetRequired<ProductAttachment> {}
export interface ProductAttachmentInsert extends ProductAttachment {}
export interface ProductAttachmentUpdate extends Partial<ProductAttachment> {}

interface ProductAttachmentType {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface ProductAttachmentTypeSelect extends SetRequired<ProductAttachmentType> {}
export interface ProductAttachmentTypeInsert extends ProductAttachmentType {}
export interface ProductAttachmentTypeUpdate extends Partial<ProductAttachmentType> {}

interface ProductAttribute {
  productId: number;
  attributeId: number;
  attributeValueId: number;
}
export interface ProductAttributeSelect extends SetRequired<ProductAttribute> {}
export interface ProductAttributeInsert extends ProductAttribute {}
export interface ProductAttributeUpdate extends Partial<ProductAttribute> {}

interface ProductAttributeRelationship {
  productId: number;
  attributeId: number;
  position: number;
  immutable: boolean;
}
export interface ProductAttributeRelationshipSelect
  extends SetRequired<ProductAttributeRelationship> {}
export interface ProductAttributeRelationshipInsert extends ProductAttributeRelationship {}
export interface ProductAttributeRelationshipUpdate extends Partial<ProductAttributeRelationship> {}

interface ProductBrand {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface ProductBrandSelect extends SetRequired<ProductBrand> {}
export interface ProductBrandInsert extends ProductBrand {}
export interface ProductBrandUpdate extends Partial<ProductBrand> {}

interface ProductCategory {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface ProductCategorySelect extends SetRequired<ProductCategory> {}
export interface ProductCategoryInsert extends ProductCategory {}
export interface ProductCategoryUpdate extends Partial<ProductCategory> {}

interface ProductCategoryAttribute {
  productCategoryId: number;
  attributeId: number;
  position: number;
}
export interface ProductCategoryAttributeSelect extends SetRequired<ProductCategoryAttribute> {}
export interface ProductCategoryAttributeInsert extends ProductCategoryAttribute {}
export interface ProductCategoryAttributeUpdate extends Partial<ProductCategoryAttribute> {}

interface ProductChangelog {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  productId: number;
  title: string;
  body?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface ProductChangelogSelect extends SetRequired<ProductChangelog> {}
export interface ProductChangelogInsert extends ProductChangelog {}
export interface ProductChangelogUpdate extends Partial<ProductChangelog> {}

interface ProductChangelogAttachment {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  productChangelogId: number;
  typeId?: number | null;
  name: string;
  src: string;
  position?: number | null;
  mimeType?: string | null;
}
export interface ProductChangelogAttachmentSelect extends SetRequired<ProductChangelogAttachment> {}
export interface ProductChangelogAttachmentInsert extends ProductChangelogAttachment {}
export interface ProductChangelogAttachmentUpdate extends Partial<ProductChangelogAttachment> {}

interface ProductChangelogAttachmentType {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface ProductChangelogAttachmentTypeSelect
  extends SetRequired<ProductChangelogAttachmentType> {}
export interface ProductChangelogAttachmentTypeInsert extends ProductChangelogAttachmentType {}
export interface ProductChangelogAttachmentTypeUpdate
  extends Partial<ProductChangelogAttachmentType> {}

interface ProductImage {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  productId: number;
  name: string;
  src: string;
  position?: number | null;
  mimeType?: string | null;
  height?: number | null;
  width?: number | null;
}
export interface ProductImageSelect extends SetRequired<ProductImage> {}
export interface ProductImageInsert extends ProductImage {}
export interface ProductImageUpdate extends Partial<ProductImage> {}

interface ProductIssue {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  closedAt?: Date | null;
  closedBy?: number | null;
  productId: number;
  title: string;
  body?: string | null;
  statusId: number;
  typeId: number;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface ProductIssueSelect extends SetRequired<ProductIssue> {}
export interface ProductIssueInsert extends ProductIssue {}
export interface ProductIssueUpdate extends Partial<ProductIssue> {}

interface ProductIssueComment {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  productIssueId: number;
  body?: string | null;
}
export interface ProductIssueCommentSelect extends SetRequired<ProductIssueComment> {}
export interface ProductIssueCommentInsert extends ProductIssueComment {}
export interface ProductIssueCommentUpdate extends Partial<ProductIssueComment> {}

interface ProductIssueStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface ProductIssueStatusSelect extends SetRequired<ProductIssueStatus> {}
export interface ProductIssueStatusInsert extends ProductIssueStatus {}
export interface ProductIssueStatusUpdate extends Partial<ProductIssueStatus> {}

interface ProductIssueType {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface ProductIssueTypeSelect extends SetRequired<ProductIssueType> {}
export interface ProductIssueTypeInsert extends ProductIssueType {}
export interface ProductIssueTypeUpdate extends Partial<ProductIssueType> {}

interface Proxy {
  id?: string;
  createdAt?: Date;
  updatedAt?: Date | null;
  checkedAt?: Date | null;
  ip: string;
  port: number;
  country: string;
  anonymity: string;
  protocol: string;
  weight?: number;
}
export interface ProxySelect extends SetRequired<Proxy> {}
export interface ProxyInsert extends Proxy {}
export interface ProxyUpdate extends Partial<Proxy> {}

interface PurchaseOrder {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  approvedAt?: Date | null;
  approvedBy: number;
  closedAt?: Date | null;
  closedBy?: number | null;
  refundedAt?: Date | null;
  refundedBy: number;
  canceledAt?: Date | null;
  canceledBy: number;
  canceledReasonId?: number | null;
  readyToShipAt?: Date | null;
  operationCenterId: number;
  paymentAccountId: number;
  webAccountId: number;
  supplierId: number;
  supplierContactId: number;
  referenceId: string;
  name: string;
  shipDate?: Date | null;
  typeId: number;
  statusId: number;
  financialStatusId: number;
  paymentTermId: number;
  shipmentServiceId: number;
  remoteIp?: string | null;
  currency: string;
  processingFee?: number | null;
  transactionFee?: number | null;
  otherFee?: number | null;
  shippingPrice?: number;
  shippingDiscount?: number;
  shippingTax?: number;
  subtotal?: number;
  discount?: number;
  discountAdjustment?: number;
  tax?: number;
  taxAdjustment?: number;
  adjustment?: number;
  total?: number;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface PurchaseOrderSelect extends SetRequired<PurchaseOrder> {}
export interface PurchaseOrderInsert extends PurchaseOrder {}
export interface PurchaseOrderUpdate extends Partial<PurchaseOrder> {}

interface PurchaseOrderItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  orderId: number;
  productId?: number | null;
  referenceId?: string | null;
  name: string;
  position?: number | null;
  quantity: number;
  quantityReceived?: number;
  quantityCanceled?: number;
  quantityRejected?: number;
  price: number;
  discount?: number;
  tax?: number;
  isTaxable?: boolean;
  isRequiresShipping?: boolean;
}
export interface PurchaseOrderItemSelect extends SetRequired<PurchaseOrderItem> {}
export interface PurchaseOrderItemInsert extends PurchaseOrderItem {}
export interface PurchaseOrderItemUpdate extends Partial<PurchaseOrderItem> {}

interface PurchaseOrderItemIdentifier {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  refundedAt?: Date | null;
  refundedBy: number;
  itemId: number;
  value: string;
}
export interface PurchaseOrderItemIdentifierSelect
  extends SetRequired<PurchaseOrderItemIdentifier> {}
export interface PurchaseOrderItemIdentifierInsert extends PurchaseOrderItemIdentifier {}
export interface PurchaseOrderItemIdentifierUpdate extends Partial<PurchaseOrderItemIdentifier> {}

interface PurchaseOrderReturn {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  canceledAt?: Date | null;
  canceledBy: number;
  closedAt?: Date | null;
  closedBy?: number | null;
  processedAt?: Date | null;
  operationCenterId: number;
  orderId: number;
  transactionId: number;
  referenceId?: string | null;
  statusId: number;
  reasonId: number;
  rmaNumber?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface PurchaseOrderReturnSelect extends SetRequired<PurchaseOrderReturn> {}
export interface PurchaseOrderReturnInsert extends PurchaseOrderReturn {}
export interface PurchaseOrderReturnUpdate extends Partial<PurchaseOrderReturn> {}

interface PurchaseOrderReturnItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  orderId: number;
  returnId: number;
  itemId: number;
  referenceId?: string | null;
  name: string;
  position: number;
  refundedPerUnit?: number | null;
  quantity: number;
  quantityRejected?: number;
  quantityCanceled?: number;
  quantityRefunded: number;
}
export interface PurchaseOrderReturnItemSelect extends SetRequired<PurchaseOrderReturnItem> {}
export interface PurchaseOrderReturnItemInsert extends PurchaseOrderReturnItem {}
export interface PurchaseOrderReturnItemUpdate extends Partial<PurchaseOrderReturnItem> {}

interface PurchaseOrderShipment {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  canceledAt?: Date | null;
  canceledBy: number;
  estimatedDeliveredAt?: Date | null;
  inTransitAt?: Date | null;
  deliveredAt?: Date | null;
  voidAt?: Date | null;
  operationCenterId: number;
  orderId: number;
  returnId?: number | null;
  transactionId?: number | null;
  courierId: number;
  referenceId?: string | null;
  price?: number;
  discount?: number;
  tax?: number;
  statusId: number;
  serviceId: number;
  packageTypeId: number;
  trackingNumber: string;
  trackingUrl?: string | null;
  label?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface PurchaseOrderShipmentSelect extends SetRequired<PurchaseOrderShipment> {}
export interface PurchaseOrderShipmentInsert extends PurchaseOrderShipment {}
export interface PurchaseOrderShipmentUpdate extends Partial<PurchaseOrderShipment> {}

interface PurchaseOrderShipmentEvent {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  orderId: number;
  shipmentId: number;
  statusId: number;
  source: string;
  message: string;
  street1?: string | null;
  street2?: string | null;
  street3?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  country?: string | null;
  latitude?: number | null;
  longitude?: number | null;
}
export interface PurchaseOrderShipmentEventSelect extends SetRequired<PurchaseOrderShipmentEvent> {}
export interface PurchaseOrderShipmentEventInsert extends PurchaseOrderShipmentEvent {}
export interface PurchaseOrderShipmentEventUpdate extends Partial<PurchaseOrderShipmentEvent> {}

interface PurchaseOrderStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface PurchaseOrderStatusSelect extends SetRequired<PurchaseOrderStatus> {}
export interface PurchaseOrderStatusInsert extends PurchaseOrderStatus {}
export interface PurchaseOrderStatusUpdate extends Partial<PurchaseOrderStatus> {}

interface PurchaseOrderTransaction {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  processedAt?: Date | null;
  operationCenterId: number;
  parentId?: number | null;
  orderId: number;
  referenceId?: string | null;
  authorization?: string | null;
  amount: number;
  paymentMethodId: number;
  currency?: string | null;
  typeId: number;
  statusId: number;
  errorCode?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  errorCodeEnumId?: number | null;
}
export interface PurchaseOrderTransactionSelect extends SetRequired<PurchaseOrderTransaction> {}
export interface PurchaseOrderTransactionInsert extends PurchaseOrderTransaction {}
export interface PurchaseOrderTransactionUpdate extends Partial<PurchaseOrderTransaction> {}

interface PurchaseOrderType {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface PurchaseOrderTypeSelect extends SetRequired<PurchaseOrderType> {}
export interface PurchaseOrderTypeInsert extends PurchaseOrderType {}
export interface PurchaseOrderTypeUpdate extends Partial<PurchaseOrderType> {}

interface ReturnDeposition {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface ReturnDepositionSelect extends SetRequired<ReturnDeposition> {}
export interface ReturnDepositionInsert extends ReturnDeposition {}
export interface ReturnDepositionUpdate extends Partial<ReturnDeposition> {}

interface ReturnStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface ReturnStatusSelect extends SetRequired<ReturnStatus> {}
export interface ReturnStatusInsert extends ReturnStatus {}
export interface ReturnStatusUpdate extends Partial<ReturnStatus> {}

interface Role {
  value: string;
  comment?: string | null;
}
export interface RoleSelect extends SetRequired<Role> {}
export interface RoleInsert extends Role {}
export interface RoleUpdate extends Partial<Role> {}

interface SalesChannel {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  operationCenterId: number;
  marketplaceId: number;
  warehouseId: number;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface SalesChannelSelect extends SetRequired<SalesChannel> {}
export interface SalesChannelInsert extends SalesChannel {}
export interface SalesChannelUpdate extends Partial<SalesChannel> {}

interface SalesChannelFeedback {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  salesChannelId: number;
  orderId?: number | null;
  customerId?: number | null;
  referenceId: string;
  referenceOrderId: string;
  referenceCustomerId: string;
  rating: number;
  content: string;
  isSuppressed?: boolean;
}
export interface SalesChannelFeedbackSelect extends SetRequired<SalesChannelFeedback> {}
export interface SalesChannelFeedbackInsert extends SalesChannelFeedback {}
export interface SalesChannelFeedbackUpdate extends Partial<SalesChannelFeedback> {}

interface SalesOrder {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  closedAt?: Date | null;
  closedBy?: number | null;
  purchasedAt?: Date | null;
  readyToShipAt?: Date | null;
  refundedAt?: Date | null;
  canceledAt?: Date | null;
  canceledReasonId?: number | null;
  operationCenterId: number;
  salesChannelId: number;
  customerId?: number | null;
  referenceId: string;
  name?: string | null;
  shipDate?: Date | null;
  statusId: number;
  financialStatusId: number;
  paymentTermId: number;
  shipmentServiceId: number;
  remoteIp?: string | null;
  currency?: string | null;
  commission?: number | null;
  referralFee?: number;
  transactionFee?: number;
  otherFee?: number;
  shippingPrice?: number;
  shippingDiscount?: number;
  shippingTax?: number;
  giftWrapPrice?: number;
  giftWrapDiscount?: number;
  giftWrapTax?: number;
  subtotal?: number;
  discount?: number;
  discountAdjustment?: number;
  tax?: number;
  taxAdjustment?: number;
  adjustment?: number;
  total?: number;
  buyerName?: string | null;
  buyerEmail?: string | null;
  buyerPhone?: string | null;
  buyerNote?: string | null;
  buyerFax?: string | null;
  shippingReceiverName?: string | null;
  shippingReceiverCompany?: string | null;
  shippingReceiverPhone?: string | null;
  shippingStreet1?: string | null;
  shippingStreet2?: string | null;
  shippingStreet3?: string | null;
  shippingCity?: string | null;
  shippingProvince?: string | null;
  shippingPostalCode?: string | null;
  shippingCountry?: string | null;
  billingPayerName?: string | null;
  billingPayerCompany?: string | null;
  billingPayerPhone?: string | null;
  billingStreet1?: string | null;
  billingStreet2?: string | null;
  billingStreet3?: string | null;
  billingCity?: string | null;
  billingProvince?: string | null;
  billingPostalCode?: string | null;
  billingCountry?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  isBusinessOrder: boolean;
  isReplacementOrder: boolean;
  isReviewRequest?: boolean;
  isVenderFulfilled: boolean;
}
export interface SalesOrderSelect extends SetRequired<SalesOrder> {}
export interface SalesOrderInsert extends SalesOrder {}
export interface SalesOrderUpdate extends Partial<SalesOrder> {}

interface SalesOrderItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  orderId: number;
  productId?: number | null;
  listingId?: number | null;
  listingVariantId?: number | null;
  referenceId?: string | null;
  name: string;
  position?: number | null;
  quantity: number;
  quantityFulfilled?: number;
  quantityCanceled?: number;
  quantityBackordered?: number;
  cost?: number | null;
  price: number;
  discount?: number;
  tax?: number;
  isTaxable?: boolean;
  isGift?: boolean;
  isRequiresShipping?: boolean;
}
export interface SalesOrderItemSelect extends SetRequired<SalesOrderItem> {}
export interface SalesOrderItemInsert extends SalesOrderItem {}
export interface SalesOrderItemUpdate extends Partial<SalesOrderItem> {}

interface SalesOrderReturn {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  canceledAt?: Date | null;
  canceledBy: number;
  closedAt?: Date | null;
  closedBy?: number | null;
  processedAt?: Date | null;
  operationCenterId: number;
  orderId: number;
  transactionId: number;
  referenceId?: string | null;
  statusId: number;
  reasonId: number;
  rmaNumber?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface SalesOrderReturnSelect extends SetRequired<SalesOrderReturn> {}
export interface SalesOrderReturnInsert extends SalesOrderReturn {}
export interface SalesOrderReturnUpdate extends Partial<SalesOrderReturn> {}

interface SalesOrderReturnItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  restockedAt?: Date | null;
  operationCenterId: number;
  orderId: number;
  returnId: number;
  itemId: number;
  referenceId?: string | null;
  name: string;
  position: number;
  depositionId: number;
  refundedPerUnit?: number | null;
  quantity: number;
  quantityReceived?: number;
  quantityRejected?: number;
  quantityCanceled?: number;
  quantityRefunded?: number;
  quantityDefective: boolean;
}
export interface SalesOrderReturnItemSelect extends SetRequired<SalesOrderReturnItem> {}
export interface SalesOrderReturnItemInsert extends SalesOrderReturnItem {}
export interface SalesOrderReturnItemUpdate extends Partial<SalesOrderReturnItem> {}

interface SalesOrderShipment {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  canceledAt?: Date | null;
  canceledBy: number;
  estimatedDeliveredAt?: Date | null;
  inTransitAt?: Date | null;
  deliveredAt?: Date | null;
  voidAt?: Date | null;
  operationCenterId: number;
  orderId: number;
  returnId?: number | null;
  transactionId?: number | null;
  courierId: number;
  referenceId?: string | null;
  statusId: number;
  serviceId: number;
  packageTypeId: number;
  currency?: string | null;
  price?: number;
  discount?: number;
  tax?: number;
  adjustment?: number;
  total?: number;
  trackingNumber: string;
  trackingUrl?: string | null;
  label?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface SalesOrderShipmentSelect extends SetRequired<SalesOrderShipment> {}
export interface SalesOrderShipmentInsert extends SalesOrderShipment {}
export interface SalesOrderShipmentUpdate extends Partial<SalesOrderShipment> {}

interface SalesOrderShipmentEvent {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  orderId: number;
  shipmentId: number;
  statusId: number;
  source: string;
  message: string;
  street1?: string | null;
  street2?: string | null;
  street3?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  country?: string | null;
  latitude?: number | null;
  longitude?: number | null;
}
export interface SalesOrderShipmentEventSelect extends SetRequired<SalesOrderShipmentEvent> {}
export interface SalesOrderShipmentEventInsert extends SalesOrderShipmentEvent {}
export interface SalesOrderShipmentEventUpdate extends Partial<SalesOrderShipmentEvent> {}

interface SalesOrderStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface SalesOrderStatusSelect extends SetRequired<SalesOrderStatus> {}
export interface SalesOrderStatusInsert extends SalesOrderStatus {}
export interface SalesOrderStatusUpdate extends Partial<SalesOrderStatus> {}

interface SalesOrderTransaction {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  processedAt?: Date | null;
  operationCenterId: number;
  parentId?: number | null;
  orderId: number;
  referenceId?: string | null;
  authorization?: string | null;
  amount: number;
  paymentMethodId: number;
  currency?: string | null;
  typeId: number;
  statusId: number;
  errorCodeId?: number | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface SalesOrderTransactionSelect extends SetRequired<SalesOrderTransaction> {}
export interface SalesOrderTransactionInsert extends SalesOrderTransaction {}
export interface SalesOrderTransactionUpdate extends Partial<SalesOrderTransaction> {}

interface Script {
  name: string;
  createdAt?: Date;
  createdBy?: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  description?: string | null;
  cron?: string | null;
  arguments?: JsonValue | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface ScriptSelect extends SetRequired<Script> {}
export interface ScriptInsert extends Script {}
export interface ScriptUpdate extends Partial<Script> {}

interface ScriptInvocation {
  id?: number;
  createdAt?: Date;
  finishedAt?: Date | null;
  scriptName: string;
  status?: string;
  ip?: string | null;
  hostname?: string | null;
  platform?: string | null;
  arguments?: JsonValue | null;
  result?: JsonValue | null;
}
export interface ScriptInvocationSelect extends SetRequired<ScriptInvocation> {}
export interface ScriptInvocationInsert extends ScriptInvocation {}
export interface ScriptInvocationUpdate extends Partial<ScriptInvocation> {}

interface ScriptStatus {
  value: string;
  comment?: string | null;
}
export interface ScriptStatusSelect extends SetRequired<ScriptStatus> {}
export interface ScriptStatusInsert extends ScriptStatus {}
export interface ScriptStatusUpdate extends Partial<ScriptStatus> {}

interface ShipmentEventType {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface ShipmentEventTypeSelect extends SetRequired<ShipmentEventType> {}
export interface ShipmentEventTypeInsert extends ShipmentEventType {}
export interface ShipmentEventTypeUpdate extends Partial<ShipmentEventType> {}

interface ShipmentService {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface ShipmentServiceSelect extends SetRequired<ShipmentService> {}
export interface ShipmentServiceInsert extends ShipmentService {}
export interface ShipmentServiceUpdate extends Partial<ShipmentService> {}

interface ShipmentStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface ShipmentStatusSelect extends SetRequired<ShipmentStatus> {}
export interface ShipmentStatusInsert extends ShipmentStatus {}
export interface ShipmentStatusUpdate extends Partial<ShipmentStatus> {}

interface Supplier {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  name: string;
  description?: string | null;
  abbr?: string | null;
  currency?: string | null;
  locale?: string | null;
  email?: string | null;
  password?: string | null;
  phone?: string | null;
  fax?: string | null;
  website?: string | null;
  credit?: number;
  address?: string | null;
  serialNumberInitial?: string | null;
  street1?: string | null;
  street2?: string | null;
  street3?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  country?: string | null;
  isEmailVerified?: boolean;
  isTaxExempt?: boolean;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface SupplierSelect extends SetRequired<Supplier> {}
export interface SupplierInsert extends Supplier {}
export interface SupplierUpdate extends Partial<Supplier> {}

interface SupplierContact {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  operationCenterId: number;
  firstName?: string | null;
  lastName?: string | null;
  jobTitle?: string | null;
  jobDepartment?: string | null;
  email?: string | null;
  officeEmail?: string | null;
  phone?: string | null;
  officePhone?: string | null;
  fax?: string | null;
  locale?: string | null;
  currency?: string | null;
  birthday?: Date | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  isAcceptMarketing?: boolean;
  isTaxExempt?: boolean;
  isEmailVerified?: boolean;
}
export interface SupplierContactSelect extends SetRequired<SupplierContact> {}
export interface SupplierContactInsert extends SupplierContact {}
export interface SupplierContactUpdate extends Partial<SupplierContact> {}

interface SupplierProduct {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  discontinuedAt?: Date | null;
  discontinuedBy: number;
  operationCenterId: number;
  supplierId: number;
  productId: number;
  cost?: number | null;
  currency?: string | null;
  weightUnit?: string | null;
  dimensionUnit?: string | null;
  productWeight?: number | null;
  productLongestSide?: number | null;
  productMediumSide?: number | null;
  productShortestSide?: number | null;
  packageWeight?: number | null;
  packageLongestSide?: number | null;
  packageMediumSide?: number | null;
  packageShortestSide?: number | null;
  quantityPerBox?: number | null;
}
export interface SupplierProductSelect extends SetRequired<SupplierProduct> {}
export interface SupplierProductInsert extends SupplierProduct {}
export interface SupplierProductUpdate extends Partial<SupplierProduct> {}

interface TransactionErrorCode {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface TransactionErrorCodeSelect extends SetRequired<TransactionErrorCode> {}
export interface TransactionErrorCodeInsert extends TransactionErrorCode {}
export interface TransactionErrorCodeUpdate extends Partial<TransactionErrorCode> {}

interface TransactionStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface TransactionStatusSelect extends SetRequired<TransactionStatus> {}
export interface TransactionStatusInsert extends TransactionStatus {}
export interface TransactionStatusUpdate extends Partial<TransactionStatus> {}

interface TransactionType {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface TransactionTypeSelect extends SetRequired<TransactionType> {}
export interface TransactionTypeInsert extends TransactionType {}
export interface TransactionTypeUpdate extends Partial<TransactionType> {}

interface Transfer {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  closedAt?: Date | null;
  closedBy?: number | null;
  shippedAt?: Date | null;
  receivedAt?: Date | null;
  processedAt?: Date | null;
  canceledAt?: Date | null;
  canceledReason: string;
  shipFromWarehouseId: number;
  shipToWarehouseId: number;
  referenceId?: string | null;
  name: string;
  statusId: number;
  shipmentServiceId: number;
  remoteIp?: string | null;
  currency?: string | null;
  processingFee?: number | null;
  transactionFee?: number | null;
  otherFee?: number | null;
  subtotal?: number;
  discount?: number;
  discountAdjustment?: number;
  tax?: number;
  taxAdjustment?: number;
  adjustment?: number;
  total?: number;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  canceledReasonEnumId?: number | null;
}
export interface TransferSelect extends SetRequired<Transfer> {}
export interface TransferInsert extends Transfer {}
export interface TransferUpdate extends Partial<Transfer> {}

interface TransferCancelReason {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface TransferCancelReasonSelect extends SetRequired<TransferCancelReason> {}
export interface TransferCancelReasonInsert extends TransferCancelReason {}
export interface TransferCancelReasonUpdate extends Partial<TransferCancelReason> {}

interface TransferItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  transferId: number;
  productId: number;
  conditionId: number;
  referenceId?: string | null;
  position: number;
  numberOfBox?: number | null;
  quantityPerBox?: number | null;
  boxWeight?: number | null;
  boxLongestSide?: number | null;
  boxMediumSide?: number | null;
  boxShortestSide?: number | null;
  quantity: number;
  quantityShipped?: number;
  quantityRejected?: number;
  quantityCanceled?: number;
  quantityReceived?: number;
}
export interface TransferItemSelect extends SetRequired<TransferItem> {}
export interface TransferItemInsert extends TransferItem {}
export interface TransferItemUpdate extends Partial<TransferItem> {}

interface TransferReturn {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  canceledAt?: Date | null;
  canceledBy: number;
  closedAt?: Date | null;
  closedBy?: number | null;
  processedAt?: Date | null;
  operationCenterId: number;
  transferId: number;
  transactionId: number;
  referenceId?: string | null;
  statusId: number;
  reason: string;
  rmaNumber?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  reasonEnumId?: number | null;
}
export interface TransferReturnSelect extends SetRequired<TransferReturn> {}
export interface TransferReturnInsert extends TransferReturn {}
export interface TransferReturnUpdate extends Partial<TransferReturn> {}

interface TransferReturnItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  restockedAt?: Date | null;
  operationCenterId: number;
  transferId: number;
  returnId: number;
  itemId: number;
  referenceId?: string | null;
  name: string;
  position: number;
  depositionId: number;
  quantity: number;
  quantityReceived?: number;
  quantityRejected?: number;
  quantityCanceled?: number;
  quantityRefunded?: number;
  quantityDefective: boolean;
}
export interface TransferReturnItemSelect extends SetRequired<TransferReturnItem> {}
export interface TransferReturnItemInsert extends TransferReturnItem {}
export interface TransferReturnItemUpdate extends Partial<TransferReturnItem> {}

interface TransferReturnReason {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface TransferReturnReasonSelect extends SetRequired<TransferReturnReason> {}
export interface TransferReturnReasonInsert extends TransferReturnReason {}
export interface TransferReturnReasonUpdate extends Partial<TransferReturnReason> {}

interface TransferShipment {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  canceledAt?: Date | null;
  canceledBy: number;
  estimatedDeliveredAt?: Date | null;
  inTransitAt?: Date | null;
  deliveredAt?: Date | null;
  voidAt?: Date | null;
  operationCenterId: number;
  transferId: number;
  transactionId?: number | null;
  courierId: number;
  referenceId?: string | null;
  price?: number;
  discount?: number;
  tax?: number;
  statusId: number;
  serviceId: number;
  packageTypeId: number;
  trackingNumber: string;
  trackingUrl?: string | null;
  label?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface TransferShipmentSelect extends SetRequired<TransferShipment> {}
export interface TransferShipmentInsert extends TransferShipment {}
export interface TransferShipmentUpdate extends Partial<TransferShipment> {}

interface TransferShipmentEvent {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  transferId: number;
  shipmentId: number;
  statusId: number;
  source: string;
  message: string;
  street1?: string | null;
  street2?: string | null;
  street3?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  country?: string | null;
  latitude?: number | null;
  longitude?: number | null;
}
export interface TransferShipmentEventSelect extends SetRequired<TransferShipmentEvent> {}
export interface TransferShipmentEventInsert extends TransferShipmentEvent {}
export interface TransferShipmentEventUpdate extends Partial<TransferShipmentEvent> {}

interface TransferStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface TransferStatusSelect extends SetRequired<TransferStatus> {}
export interface TransferStatusInsert extends TransferStatus {}
export interface TransferStatusUpdate extends Partial<TransferStatus> {}

interface TransferTransaction {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  processedAt?: Date | null;
  operationCenterId: number;
  parentId?: number | null;
  transferId: number;
  referenceId?: string | null;
  authorization?: string | null;
  amount: number;
  paymentMethodId: number;
  currency?: string | null;
  typeId: number;
  statusId: number;
  errorCodeId?: number | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface TransferTransactionSelect extends SetRequired<TransferTransaction> {}
export interface TransferTransactionInsert extends TransferTransaction {}
export interface TransferTransactionUpdate extends Partial<TransferTransaction> {}

interface UnitDimension {
  value: string;
  comment?: string | null;
}
export interface UnitDimensionSelect extends SetRequired<UnitDimension> {}
export interface UnitDimensionInsert extends UnitDimension {}
export interface UnitDimensionUpdate extends Partial<UnitDimension> {}

interface UnitWeight {
  value: string;
  comment?: string | null;
}
export interface UnitWeightSelect extends SetRequired<UnitWeight> {}
export interface UnitWeightInsert extends UnitWeight {}
export interface UnitWeightUpdate extends Partial<UnitWeight> {}

interface User {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  lastLoginAt?: Date | null;
  username: string;
  password: string;
  firstName?: string | null;
  lastName?: string | null;
  title?: string | null;
  department?: string | null;
  email?: string | null;
  officeEmail?: string | null;
  phone?: string | null;
  officePhone?: string | null;
  skype?: string | null;
  fax?: string | null;
  locale?: string | null;
  currency?: string | null;
  birthday?: Date | null;
  employeeLevelId?: number | null;
  employeeTypeId?: number | null;
  paidTimeOff?: number | null;
  refreshToken?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  isEmailVerified?: boolean;
}
export interface UserSelect extends SetRequired<User> {}
export interface UserInsert extends User {}
export interface UserUpdate extends Partial<User> {}

interface UserAudit {
  id?: number;
  createdAt?: Date;
  userId: number;
  ip?: string | null;
  isSuccess: boolean;
}
export interface UserAuditSelect extends SetRequired<UserAudit> {}
export interface UserAuditInsert extends UserAudit {}
export interface UserAuditUpdate extends Partial<UserAudit> {}

interface UserOperationCenter {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  userId: number;
  operationCenterId: number;
  isDefault?: boolean;
}
export interface UserOperationCenterSelect extends SetRequired<UserOperationCenter> {}
export interface UserOperationCenterInsert extends UserOperationCenter {}
export interface UserOperationCenterUpdate extends Partial<UserOperationCenter> {}

interface UserPaidTimeOff {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  userId: number;
  reason: string;
  adjustment: number;
}
export interface UserPaidTimeOffSelect extends SetRequired<UserPaidTimeOff> {}
export interface UserPaidTimeOffInsert extends UserPaidTimeOff {}
export interface UserPaidTimeOffUpdate extends Partial<UserPaidTimeOff> {}

interface UserRole {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  userId: number;
  role: string;
  isDefault?: boolean;
}
export interface UserRoleSelect extends SetRequired<UserRole> {}
export interface UserRoleInsert extends UserRole {}
export interface UserRoleUpdate extends Partial<UserRole> {}

interface UserToken {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  expiresAt: Date;
  userId: number;
  type: string;
  value: string;
}
export interface UserTokenSelect extends SetRequired<UserToken> {}
export interface UserTokenInsert extends UserToken {}
export interface UserTokenUpdate extends Partial<UserToken> {}

interface UserTokenType {
  value: string;
  comment?: string | null;
}
export interface UserTokenTypeSelect extends SetRequired<UserTokenType> {}
export interface UserTokenTypeInsert extends UserTokenType {}
export interface UserTokenTypeUpdate extends Partial<UserTokenType> {}

interface Warehouse {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface WarehouseSelect extends SetRequired<Warehouse> {}
export interface WarehouseInsert extends Warehouse {}
export interface WarehouseUpdate extends Partial<Warehouse> {}

interface WebAccount {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  operationCenterId: number;
  ownerId?: number | null;
  name: string;
  description?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  website?: string | null;
  username?: string | null;
  password?: string | null;
  email?: string | null;
  phone?: string | null;
}
export interface WebAccountSelect extends SetRequired<WebAccount> {}
export interface WebAccountInsert extends WebAccount {}
export interface WebAccountUpdate extends Partial<WebAccount> {}

interface WholesaleAccount {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  operationCenterId: number;
  salesRepresentativeId: number;
  statusId: number;
  typeId?: number | null;
  roleId?: number | null;
  levelId?: number | null;
  channelId?: number | null;
  businessName: string;
  businessNameAlias?: string | null;
  businessDescription?: string | null;
  businessEmail?: string | null;
  businessPhone?: string | null;
  businessFax?: string | null;
  businessWebsite?: string | null;
  payableContactName?: string | null;
  payableContactEmail?: string | null;
  payableContactPhone?: string | null;
  password?: string | null;
  storeCredit?: number;
  taxInformation?: JsonValue | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface WholesaleAccountSelect extends SetRequired<WholesaleAccount> {}
export interface WholesaleAccountInsert extends WholesaleAccount {}
export interface WholesaleAccountUpdate extends Partial<WholesaleAccount> {}

interface WholesaleAccountChannel {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface WholesaleAccountChannelSelect extends SetRequired<WholesaleAccountChannel> {}
export interface WholesaleAccountChannelInsert extends WholesaleAccountChannel {}
export interface WholesaleAccountChannelUpdate extends Partial<WholesaleAccountChannel> {}

interface WholesaleAccountLevel {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface WholesaleAccountLevelSelect extends SetRequired<WholesaleAccountLevel> {}
export interface WholesaleAccountLevelInsert extends WholesaleAccountLevel {}
export interface WholesaleAccountLevelUpdate extends Partial<WholesaleAccountLevel> {}

interface WholesaleAccountRole {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface WholesaleAccountRoleSelect extends SetRequired<WholesaleAccountRole> {}
export interface WholesaleAccountRoleInsert extends WholesaleAccountRole {}
export interface WholesaleAccountRoleUpdate extends Partial<WholesaleAccountRole> {}

interface WholesaleAccountStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface WholesaleAccountStatusSelect extends SetRequired<WholesaleAccountStatus> {}
export interface WholesaleAccountStatusInsert extends WholesaleAccountStatus {}
export interface WholesaleAccountStatusUpdate extends Partial<WholesaleAccountStatus> {}

interface WholesaleAccountType {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface WholesaleAccountTypeSelect extends SetRequired<WholesaleAccountType> {}
export interface WholesaleAccountTypeInsert extends WholesaleAccountType {}
export interface WholesaleAccountTypeUpdate extends Partial<WholesaleAccountType> {}

interface WholesaleContact {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  deactivatedAt?: Date | null;
  deactivatedBy?: number | null;
  operationCenterId: number;
  accountId: number;
  defaultBillingAddressId?: number | null;
  defaultShippingAddressId?: number | null;
  firstName?: string | null;
  lastName?: string | null;
  alias?: string | null;
  jobTitle?: string | null;
  jobDepartment?: string | null;
  email?: string | null;
  officeEmail?: string | null;
  phone?: string | null;
  officePhone?: string | null;
  fax?: string | null;
  locale?: string | null;
  currency?: string | null;
  birthday?: Date | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  isAcceptMarketing?: boolean;
  isTaxExempt?: boolean;
  isEmailVerified?: boolean;
}
export interface WholesaleContactSelect extends SetRequired<WholesaleContact> {}
export interface WholesaleContactInsert extends WholesaleContact {}
export interface WholesaleContactUpdate extends Partial<WholesaleContact> {}

interface WholesaleContactAddress {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  contactId: number;
  typeId: number;
  name: string;
  company?: string | null;
  phone?: string | null;
  street1?: string | null;
  street2?: string | null;
  street3?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  country?: string | null;
  vatId?: string | null;
  vatRequestDate?: Date | null;
  vatRequestId?: string | null;
  isVatValid?: boolean | null;
  isVatRequestSuccess?: boolean | null;
  isResidential: boolean;
  raw?: string | null;
}
export interface WholesaleContactAddressSelect extends SetRequired<WholesaleContactAddress> {}
export interface WholesaleContactAddressInsert extends WholesaleContactAddress {}
export interface WholesaleContactAddressUpdate extends Partial<WholesaleContactAddress> {}

interface WholesaleOrder {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  closedAt?: Date | null;
  closedBy?: number | null;
  purchasedAt?: Date | null;
  readyToShipAt?: Date | null;
  refundedAt?: Date | null;
  canceledAt?: Date | null;
  canceledReasonId?: number | null;
  operationCenterId: number;
  salesRepresentativeId: number;
  quoteId?: number | null;
  accountId?: number | null;
  contactId?: number | null;
  name: string;
  shipDate?: Date | null;
  statusId: number;
  financialStatusId: number;
  paymentTermId: number;
  shipmentServiceId: number;
  remoteIp?: string | null;
  currency?: string | null;
  commission?: number | null;
  referralFee?: number;
  transactionFee?: number;
  otherFee?: number;
  shippingPrice?: number;
  shippingDiscount?: number;
  shippingTax?: number;
  giftWrapPrice?: number;
  giftWrapDiscount?: number;
  giftWrapTax?: number;
  subtotal?: number;
  discount?: number;
  discountAdjustment?: number;
  tax?: number;
  taxAdjustment?: number;
  total?: number;
  buyerName?: string | null;
  buyerEmail?: string | null;
  buyerPhone?: string | null;
  buyerNote?: string | null;
  buyerFax?: string | null;
  shippingReceiverName?: string | null;
  shippingReceiverCompany?: string | null;
  shippingReceiverPhone?: string | null;
  shippingStreet1?: string | null;
  shippingStreet2?: string | null;
  shippingStreet3?: string | null;
  shippingCity?: string | null;
  shippingProvince?: string | null;
  shippingPostalCode?: string | null;
  shippingCountry?: string | null;
  billingPayerName?: string | null;
  billingPayerCompany?: string | null;
  billingPayerPhone?: string | null;
  billingStreet1?: string | null;
  billingStreet2?: string | null;
  billingStreet3?: string | null;
  billingCity?: string | null;
  billingProvince?: string | null;
  billingPostalCode?: string | null;
  billingCountry?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
  isBusinessOrder?: boolean;
  isReplacementOrder?: boolean;
  isReviewRequest?: boolean;
}
export interface WholesaleOrderSelect extends SetRequired<WholesaleOrder> {}
export interface WholesaleOrderInsert extends WholesaleOrder {}
export interface WholesaleOrderUpdate extends Partial<WholesaleOrder> {}

interface WholesaleOrderItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  orderId: number;
  productId?: number | null;
  listingId?: number | null;
  listingVariantId?: number | null;
  referenceId?: string | null;
  name: string;
  position?: number | null;
  quantity: number;
  quantityFulfilled?: number;
  quantityCanceled?: number;
  quantityBackordered?: number;
  cost?: number | null;
  price: number;
  discount?: number;
  tax?: number;
  isTaxable?: boolean;
  isGift?: boolean;
  isRequiresShipping?: boolean;
}
export interface WholesaleOrderItemSelect extends SetRequired<WholesaleOrderItem> {}
export interface WholesaleOrderItemInsert extends WholesaleOrderItem {}
export interface WholesaleOrderItemUpdate extends Partial<WholesaleOrderItem> {}

interface WholesaleOrderQuote {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  convertedAt?: Date | null;
  convertedBy: number;
  closedAt?: Date | null;
  closedBy?: number | null;
  operationCenterId: number;
  salesRepresentativeId: number;
  accountId?: number | null;
  contactId?: number | null;
  shipDate?: Date | null;
  paymentTerm?: string | null;
  shipmentService?: string | null;
  remoteIp?: string | null;
  currency?: string | null;
  shippingPrice?: number;
  shippingDiscount?: number;
  shippingTax?: number;
  giftWrapPrice?: number;
  giftWrapDiscount?: number;
  giftWrapTax?: number;
  subtotal?: number;
  discount?: number;
  tax?: number;
  total?: number;
  buyerName?: string | null;
  buyerEmail?: string | null;
  buyerPhone?: string | null;
  buyerNote?: string | null;
  buyerFax?: string | null;
  shippingReceiverName?: string | null;
  shippingReceiverCompany?: string | null;
  shippingReceiverPhone?: string | null;
  shippingStreet1?: string | null;
  shippingStreet2?: string | null;
  shippingStreet3?: string | null;
  shippingCity?: string | null;
  shippingProvince?: string | null;
  shippingPostalCode?: string | null;
  shippingCountry?: string | null;
  billingPayerName?: string | null;
  billingPayerCompany?: string | null;
  billingPayerPhone?: string | null;
  billingStreet1?: string | null;
  billingStreet2?: string | null;
  billingStreet3?: string | null;
  billingCity?: string | null;
  billingProvince?: string | null;
  billingPostalCode?: string | null;
  billingCountry?: string | null;
  paymentTermEnumId?: number | null;
  shipmentServiceEnumId?: number | null;
}
export interface WholesaleOrderQuoteSelect extends SetRequired<WholesaleOrderQuote> {}
export interface WholesaleOrderQuoteInsert extends WholesaleOrderQuote {}
export interface WholesaleOrderQuoteUpdate extends Partial<WholesaleOrderQuote> {}

interface WholesaleOrderQuoteItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  quoteId: number;
  productId?: number | null;
  listingId?: number | null;
  listingVariantId?: number | null;
  referenceId?: string | null;
  name: string;
  position: number;
  quantity: number;
  price: number;
  discount?: number;
  tax?: number;
  isTaxable?: boolean;
  isGift?: boolean;
  isRequiresShipping?: boolean;
}
export interface WholesaleOrderQuoteItemSelect extends SetRequired<WholesaleOrderQuoteItem> {}
export interface WholesaleOrderQuoteItemInsert extends WholesaleOrderQuoteItem {}
export interface WholesaleOrderQuoteItemUpdate extends Partial<WholesaleOrderQuoteItem> {}

interface WholesaleOrderReturn {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  canceledAt?: Date | null;
  canceledBy: number;
  closedAt?: Date | null;
  closedBy?: number | null;
  processedAt?: Date | null;
  operationCenterId: number;
  orderId: number;
  transactionId: number;
  referenceId?: string | null;
  statusId: number;
  reasonId: number;
  rmaNumber?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface WholesaleOrderReturnSelect extends SetRequired<WholesaleOrderReturn> {}
export interface WholesaleOrderReturnInsert extends WholesaleOrderReturn {}
export interface WholesaleOrderReturnUpdate extends Partial<WholesaleOrderReturn> {}

interface WholesaleOrderReturnItem {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  restockedAt?: Date | null;
  operationCenterId: number;
  returnId: number;
  orderId: number;
  itemId: number;
  referenceId?: string | null;
  name: string;
  position: number;
  depositionId: number;
  refundedPerUnit?: number | null;
  quantity: number;
  quantityReceived?: number;
  quantityRejected?: number;
  quantityCanceled?: number;
  quantityRefunded?: number;
  quantityDefective: boolean;
}
export interface WholesaleOrderReturnItemSelect extends SetRequired<WholesaleOrderReturnItem> {}
export interface WholesaleOrderReturnItemInsert extends WholesaleOrderReturnItem {}
export interface WholesaleOrderReturnItemUpdate extends Partial<WholesaleOrderReturnItem> {}

interface WholesaleOrderShipment {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  canceledAt?: Date | null;
  canceledBy: number;
  estimatedDeliveredAt?: Date | null;
  inTransitAt?: Date | null;
  deliveredAt?: Date | null;
  voidAt?: Date | null;
  operationCenterId: number;
  orderId: number;
  returnId?: number | null;
  transactionId?: number | null;
  courierId: number;
  referenceId?: string | null;
  price?: number;
  discount?: number;
  tax?: number;
  statusId: number;
  serviceId: number;
  packageTypeId: number;
  trackingNumber: string;
  trackingUrl?: string | null;
  label?: string | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface WholesaleOrderShipmentSelect extends SetRequired<WholesaleOrderShipment> {}
export interface WholesaleOrderShipmentInsert extends WholesaleOrderShipment {}
export interface WholesaleOrderShipmentUpdate extends Partial<WholesaleOrderShipment> {}

interface WholesaleOrderShipmentEvent {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  operationCenterId: number;
  orderId: number;
  shipmentId: number;
  statusId: number;
  source: string;
  message: string;
  street1?: string | null;
  street2?: string | null;
  street3?: string | null;
  city?: string | null;
  province?: string | null;
  postalCode?: string | null;
  country?: string | null;
  latitude?: number | null;
  longitude?: number | null;
}
export interface WholesaleOrderShipmentEventSelect
  extends SetRequired<WholesaleOrderShipmentEvent> {}
export interface WholesaleOrderShipmentEventInsert extends WholesaleOrderShipmentEvent {}
export interface WholesaleOrderShipmentEventUpdate extends Partial<WholesaleOrderShipmentEvent> {}

interface WholesaleOrderStatus {
  id?: number;
  value: string;
  comment?: string | null;
}
export interface WholesaleOrderStatusSelect extends SetRequired<WholesaleOrderStatus> {}
export interface WholesaleOrderStatusInsert extends WholesaleOrderStatus {}
export interface WholesaleOrderStatusUpdate extends Partial<WholesaleOrderStatus> {}

interface WholesaleOrderTransaction {
  id?: number;
  createdAt?: Date;
  createdBy: number;
  updatedAt?: Date | null;
  updatedBy?: number | null;
  deletedAt?: Date | null;
  deletedBy?: number | null;
  processedAt?: Date | null;
  operationCenterId: number;
  parentId?: number | null;
  orderId: number;
  referenceId?: string | null;
  authorization?: string | null;
  amount: number;
  paymentMethodId: number;
  currency?: string | null;
  typeId: number;
  statusId: number;
  errorCodeId?: number | null;
  tags?: string | null;
  note?: string | null;
  metadata?: JsonValue | null;
}
export interface WholesaleOrderTransactionSelect extends SetRequired<WholesaleOrderTransaction> {}
export interface WholesaleOrderTransactionInsert extends WholesaleOrderTransaction {}
export interface WholesaleOrderTransactionUpdate extends Partial<WholesaleOrderTransaction> {}

interface CompetitorListingPriceHistory {
  competitorListingId?: number | null;
  date?: Date | null;
  price?: number | null;
  newPrice?: number | null;
}
export interface CompetitorListingPriceHistorySelect
  extends SetRequired<CompetitorListingPriceHistory> {}

interface CompetitorListingRatingHistory {
  competitorListingId?: number | null;
  date?: Date | null;
  rating?: number | null;
  newRating?: number | null;
}
export interface CompetitorListingRatingHistorySelect
  extends SetRequired<CompetitorListingRatingHistory> {}

interface ComputerInventory {
  productId?: number | null;
  parentId?: number | null;
  color?: string | null;
  ram?: string | null;
  cpu?: string | null;
  hdd?: string | null;
  os?: string | null;
  dvd?: string | null;
  graphicCard?: string | null;
  screenSize?: string | null;
  model?: string | null;
  touchable?: string | null;
  ssd?: string | null;
  fingerprint?: string | null;
  bluetooth?: string | null;
  resolution?: string | null;
  sugarlandInventoryWarehouseId?: number | null;
  sugarlandInventoryAvailable?: number | null;
  sugarlandInventoryIncoming?: number | null;
  sugarlandInventoryReserved?: number | null;
  sugarlandInventoryTemporary?: number | null;
  sugarlandInventoryDefective?: number | null;
  sugarlandInventoryLocation?: string | null;
}
export interface ComputerInventorySelect extends SetRequired<ComputerInventory> {}

interface Permission {
  table?: string | null;
  role?: string | null;
  permissions?: JsonValue | null;
}
export interface PermissionSelect extends SetRequired<Permission> {}

interface PgStatStatements {
  userid?: number | null;
  dbid?: number | null;
  queryid?: number | null;
  query?: string | null;
  calls?: number | null;
  totalTime?: number | null;
  minTime?: number | null;
  maxTime?: number | null;
  meanTime?: number | null;
  stddevTime?: number | null;
  rows?: number | null;
  sharedBlksHit?: number | null;
  sharedBlksRead?: number | null;
  sharedBlksDirtied?: number | null;
  sharedBlksWritten?: number | null;
  localBlksHit?: number | null;
  localBlksRead?: number | null;
  localBlksDirtied?: number | null;
  localBlksWritten?: number | null;
  tempBlksRead?: number | null;
  tempBlksWritten?: number | null;
  blkReadTime?: number | null;
  blkWriteTime?: number | null;
}
export interface PgStatStatementsSelect extends SetRequired<PgStatStatements> {}

interface ProductInventory {
  id?: number | null;
  image?: string | null;
  updatedAt?: Date | null;
  discontinuedAt?: Date | null;
  modelNumber?: string | null;
  price?: number | null;
  name?: string | null;
  brandId?: number | null;
  brandName?: string | null;
  categoryId?: number | null;
  categoryName?: string | null;
  sugarlandInventoryWarehouseId?: number | null;
  sugarlandInventoryAvailable?: number | null;
  sugarlandInventoryIncoming?: number | null;
  sugarlandInventoryReserved?: number | null;
  sugarlandInventoryTemporary?: number | null;
  sugarlandInventoryDefective?: number | null;
  sugarlandInventoryLocation?: string | null;
  shenzhenInventoryWarehouseId?: number | null;
  shenzhenInventoryAvailable?: number | null;
  shenzhenInventoryIncoming?: number | null;
  shenzhenInventoryReserved?: number | null;
  shenzhenInventoryTemporary?: number | null;
  shenzhenInventoryDefective?: number | null;
  amazonUsInventoryWarehouseId?: number | null;
  amazonUsInventoryAvailable?: number | null;
  amazonUsInventoryIncoming?: number | null;
  amazonUsInventoryReserved?: number | null;
  amazonUsInventoryTemporary?: number | null;
  amazonUsInventoryDefective?: number | null;
  amazonUkInventoryWarehouseId?: number | null;
  amazonUkInventoryAvailable?: number | null;
  amazonUkInventoryIncoming?: number | null;
  amazonUkInventoryReserved?: number | null;
  amazonUkInventoryTemporary?: number | null;
  amazonUkInventoryDefective?: number | null;
}
export interface ProductInventorySelect extends SetRequired<ProductInventory> {}

interface Review {
  id?: number | null;
  createdAt?: Date | null;
  updatedAt?: Date | null;
  operationCenterId?: number | null;
  brandId?: number | null;
  brandName?: string | null;
  salesChanenlName?: string | null;
  salesChannelId?: number | null;
  productId?: number | null;
  productName?: string | null;
  listingReferenceId?: string | null;
  listingId?: number | null;
  referenceId?: string | null;
  referenceCustomerId?: string | null;
  src?: string | null;
  date?: Date | null;
  title?: string | null;
  content?: string | null;
  reviewer?: string | null;
  rating?: number | null;
  images?: JsonValue | null;
  videos?: JsonValue | null;
  helpfulCount?: number | null;
  isApproved?: boolean | null;
  isVerified?: boolean | null;
}
export interface ReviewSelect extends SetRequired<Review> {}
